AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/WordArray:
  Enabled: true
  EnforcedStyle: brackets